### ISSUE TITLE
Test automatically the building process

### ISSUE THREAD

**Issue by pc3356** [hypergraphql/hypergraphql#13]
_From @SkypLabs on May 31, 2018 15:50_

Hi,

This issue follows up with #29.

I suggest to add a way to test automatically the building process and, if any, to execute all the unit tests in order to track issues in terms of misconfiguration, dependency problem or regression (see #19).

The pull request #29 suggests using Travis CI to carry out this task. Travis CI is a free, open-source and easy-to-use hosted continuous integration and deployment system. It perfectly fits the needs of an open-source project such as HyperGraphQL.

If you have any questions about Travis CI or the continuous integration and deployment systems in general, I would be happy to answer you.

Thanks.

_Copied from original issue: semantic-integration/hypergraphql#32_

**Comment by pc3356** [comment]
This is now available on Travis: https://travis-ci.org/hypergraphql/hypergraphql

**Comment by pc3356** [comment]
My apologies; I didn't know about that one, so I'll make sure I do in future.

**Comment by SkypLabs** [comment]
No worries :+1: It was just to let you know about this feature.

It is mainly used by projects accepting patches only. You submit your patch via email and a project contributor commits it on your behalf. It is the case of [Open vSwitch](https://docs.openvswitch.org/en/latest/internals/contributing/submitting-patches/) for example.
