### ISSUE TITLE
Custom scalar types

### ISSUE THREAD

**Issue by earcam** [hypergraphql/hypergraphql#21]
Hi,

Custom scalar types don’t appear to be supported.
Attempting to define ‘scalar anyURI’ results in a null pointer exception in HGQLSchema.getGraphQLOutputType line 305

Not a show stopper as can just use the built-in String, but certainly a nice-to-have

Thanks

**Comment by pc3356** [comment]
Hello,

This is certainly something we're looking into, and would like to introduce as full a feature set as possible as soon as we have some time to devote to this.

I'll make sure it's on the list.

Many thanks,
