### ISSUE TITLE
The about link to hypergraphql

### ISSUE THREAD

**Issue by OyvindLGjesdal** [hypergraphql/hypergraphql#34]
I was looking for the documentation page and noticed that the link in the about section `http://hypergraphql.org` on the right side, under the **About** section returns 
```
400 Bad Request
nginx
```
www.hypergraphql.org works :)

**Comment by pc3356** [comment]
Thanks for this; I'll get it sorted as soon as I have some time!

**Comment by pc3356** [comment]
Link updated
